### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [mgibbs189/cfs-synchronize#2]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by mgibbs189** [comment]
Hi,

The license (GPLv2) is specified at the top of the main PHP file.

**Comment by karan** [comment]
Ah. My bad!

Although, you should consider adding a `LICENSE` file too! But thanks for being a good samaritan. :smile:
